jobs:
- job: Build
  pool:
    vmImage: 'windows-latest'

  steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '4.x.x'  # Ange rätt .NET SDK-version

  - task: Cache@2
    inputs:
      key: 'nuget | $(Agent.OS) | **/*.csproj'  # Nyckel baserat på operativsystem och projektfiler
      path: ~/.nuget/packages
      cacheHitVar: 'NUGET_CACHE_RESTORED'  # Spara resultatet av cacheträff

  - script: |
      nuget restore
    displayName: 'Restore NuGet packages'
    condition: ne(variables.NUGET_CACHE_RESTORED, 'true')  # Kör endast om cacheträff inte hittades

  - task: VSBuild@1
    inputs:
      solution: '**/*.sln'
      msbuildArchitecture: 'x64'
