trigger:
  branches:
    include:
      - main  # Ändra om du använder en annan branch

pool:
  vmImage: 'windows-latest'  # .NET Framework kräver en Windows-miljö

steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '4.7.x'  # Använd den version du vill ha för .NET Framework 4.7.x

  - task: NuGetCommand@2
    inputs:
      restoreSolution: true

  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        $versionFile = 'version.txt'
        $version = Get-Content $versionFile
        
        # Dela upp versionsnumret
        $parts = $version -split '\.'
        $major = [int]$parts[0]
        $minor = [int]$parts[1]
        $build = [int]$parts[2]
        $revision = [int]$parts[3]
        
        # Inkrementera byggnummer och sätt revision till 0
        $build++
        $newVersion = "$major.$minor.$build.0"
        
        # Skriv tillbaka den nya versionen till version.txt
        Set-Content $versionFile $newVersion
        
        Write-Host "New version: $newVersion"
        echo "##vso[task.setvariable variable=versionNumber]$newVersion"
    displayName: 'Inkrementera versionsnummer'

  - task: VSBuild@1
    inputs:
      solution: '**\TrainingManagerBuilder.csproj'
      msbuildArgs: '/p:Configuration=Release'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(Build.SourcesDirectory)/bin/Release'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/TMBuilder_$(versionNumber).zip'
      replaceExistingArchive: true

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)/TMBuilder_$(versionNumber).zip'
      artifactName: 'drop'
      publishLocation: 'Container'

  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        git config --local user.email "action@azuredevops.com"
        git config --local user.name "Azure DevOps"
        git add version.txt
        git commit -m "Increment version to $(versionNumber)"
        git push
    displayName: 'Commit updated version file'
