name: Build .NET Framework 4.7.2 project

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest  # .NET Framework kräver en Windows-miljö

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Install .NET Framework 4.7.2 Developer Pack
      run: |
        choco install netfx-4.7.2-devpack

    - name: Restore NuGet packages
      run: nuget restore

    - name: Build solution
      run: msbuild TrainingManagerBuilder.csproj /p:Configuration=Release

    - name: Zip output files
      run: |
        Compress-Archive -Path $env:RUNNER_TEMP\* -DestinationPath $env:RUNNER_TEMP\output.zip
      shell: pwsh

    - name: Deploy to Dropbox
      uses: aTable/deploy-to-dropbox@v1.0.7
      with:
        DROPBOX_ACCESS_TOKEN: ${{ secrets.DROPBOX_ACCESS_TOKEN }}  # Access Token från Dropbox
        GLOB: '**/*.zip'  # Glob för att matcha alla zip-filer i projektet
        DROPBOX_DESTINATION_PATH_PREFIX: '/Appar/CD-github/'  # Sökvägen i Dropbox där filerna ska laddas upp
        DEBUG: 'false'
            
          
        
