name: Build .NET Framework 4.7.2 project

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest  # .NET Framework kräver en Windows-miljö

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Install .NET Framework 4.7.2 Developer Pack
      run: |
        choco install netfx-4.7.2-devpack

    - name: Restore NuGet packages
      run: nuget restore

    - name: Build solution
      run: msbuild TrainingManagerBuilder.csproj /p:Configuration=Release

    - name: Zip output files
      run: |
        Compress-Archive -Path $env:RUNNER_TEMP\* -DestinationPath $env:RUNNER_TEMP\output.zip
      shell: pwsh

    - name: Upload artifact to Dropbox
      uses: satterly/dropbox-upload-action@v1
      with:
        dropbox-access-token: ${{ secrets.DROPBOX_ACCESS_TOKEN }}
        dropbox-path: /Appar/CD-github/output.zip
        local-path: ./build/output/output.zip
