name: Build .NET Framework 4.7.2 project

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest  # .NET Framework kräver en Windows-miljö

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Install .NET Framework 4.7.2 Developer Pack
      run: |
        choco install netfx-4.7.2-devpack

    - name: Restore NuGet packages
      run: nuget restore

    - name: Build solution
      run: msbuild TrainingManagerBuilder.csproj /p:Configuration=Release

    - name: Create zip folder
      run: |
        mkdir $env:RUNNER_TEMP\output

    - name: Zip output files
      run: |
        Compress-Archive -Path ./bin/Release/* -DestinationPath $env:RUNNER_TEMP\output\output.zip
      shell: pwsh

    - name: Verify zip file creation
      run: |
        if (Test-Path "$env:RUNNER_TEMP\output\output.zip") { 
          Write-Host "Zip file exists."
          Get-ChildItem $env:RUNNER_TEMP\output\output.zip | Format-Table Name, Length
        } else { 
          Write-Host "Zip file does not exist." 
        }
      shell: pwsh

    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: build-output
        path: $env:RUNNER_TEMP\output\output.zip
