name: Build .NET Framework 4.7.2 project

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest  # .NET Framework kräver en Windows-miljö

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Install .NET Framework 4.7.2 Developer Pack
      run: |
        choco install netfx-4.7.2-devpack

    - name: Restore NuGet packages
      run: nuget restore

    - name: Build solution
      run: msbuild TrainingManagerBuilder.csproj /p:Configuration=Release

    - name: Create zip folder
      run: |
        mkdir $env:RUNNER_TEMP\output

    - name: Zip output files
      run: |
        Compress-Archive -Path ./bin/Release/* -DestinationPath $env:RUNNER_TEMP\output\output.zip
      shell: pwsh

    - name: Verify zip file creation and set output path
      id: verify-zip
      run: |
        if (Test-Path "$env:RUNNER_TEMP\output\output.zip") { 
          Write-Host "Zip file exists."
          Get-ChildItem $env:RUNNER_TEMP\output\output.zip | Format-Table Name, Length
          echo "::set-output name=zip_path::$env:RUNNER_TEMP\output\output.zip"
        } else { 
          Write-Host "Zip file does not exist." 
          exit 1
        }
      shell: pwsh

    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: build-output
        path: ${{ steps.verify-zip.outputs.zip_path }}

    - name: Upload to Dropbox
      uses: aTable/deploy-to-dropbox@v1.0.7
      with:
        DROPBOX_ACCESS_TOKEN: ${{ secrets.DROPBOX_ACCESS_TOKEN }}
        GLOB: ${{ steps.verify-zip.outputs.zip_path }}  # Använd korrekt sökväg här
        DROPBOX_DESTINATION_PATH_PREFIX: '/Appar/CD-github/'
        DEBUG: 'true'
