name: Build .NET Framework 4.7.2 project

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest  # .NET Framework kräver en Windows-miljö

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Install .NET Framework 4.7.2 Developer Pack
      run: |
        choco install netfx-4.7.2-devpack

    - name: Restore NuGet packages
      run: nuget restore

    - name: Build solution
      run: msbuild TrainingManagerBuilder.csproj /p:Configuration=Release

    - name: Create zip folder
      run: |
        mkdir $env:RUNNER_TEMP\output

    - name: Zip output files
      run: |
        Compress-Archive -Path ./YourBuildFolder/* -DestinationPath $env:RUNNER_TEMP\output\output.zip
      shell: pwsh

    - name: Verify zip file creation
      run: |
        if (Test-Path "$env:RUNNER_TEMP\output\output.zip") { Write-Host "Zip file exists." } else { Write-Host "Zip file does not exist." }
      shell: pwsh

    - name: Deploy to Dropbox
      uses: aTable/deploy-to-dropbox@v1.0.7
      with:
        DROPBOX_ACCESS_TOKEN: ${{ secrets.DROPBOX_ACCESS_TOKEN }}  # Access Token från Dropbox
        GLOB: '$env:RUNNER_TEMP/output/output.zip'  # Sökvägen till zip-filen
        DROPBOX_DESTINATION_PATH_PREFIX: '/Appar/CD-github/'  # Sökvägen i Dropbox
        DEBUG: 'true'
